Tasks of 3-module
js-tasks-ru/jsbasic-20230911_anton-ivanichenko pull request #4
Opened 2023-09-24 14:32 UTC by AntonIvanichenko

2023-09-24 14:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-25 10:10 UTC, SinimaWath requested changes

2023-09-25 10:10 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  if (strArray.length > 1) return strArray.join('\n');
эта проверка лишняя, если длинна массива будет равна 1, то join ничего не сделает

2023-09-25 12:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-27 18:41 UTC, SinimaWath approved these changes

2023-09-27 18:41 UTC, merged