4 module' tasks
js-tasks-ru/jsbasic-20230911_anton-ivanichenko pull request #5
Opened 2023-10-01 10:53 UTC by AntonIvanichenko

2023-10-02 14:41 UTC, SinimaWath commented
у тебя есть конфликты

Сделай:
- `git pull upstream master`

 - Пофикси конфликт, убери в файлике разделители `=====` `<===` и т,д. Если их нет, переходи к след шагу
 
 - Сделай коммит и запушь
 
 
 Вот тут хороший пример: https://www.youtube.com/watch?v=PXK1hIifpWU

2023-10-03 07:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-03 08:22 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-10-04 21:08 UTC, SinimaWath requested changes
тут ок, но давай не удалять добавленные задачи. Их нужно вернуть

2023-10-07 19:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-10-07 20:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-10-11 07:16 UTC, AntonIvanichenko commented
привет, можно до проверки и слияния добавлять задачи и подгружать себе или будет конфликт? а то я жду проверки и домашка копится

2023-10-12 10:14 UTC, SinimaWath approved these changes

2023-10-12 10:16 UTC, merged